config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :domos, except: [:index] do
    collection do 
      get :login
      get :top
    end

  end

  root to: 'domos#top'
  
  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/domo.rb
class Domo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def hello
    render html: "hello, world"
  end
end

app/controllers/domos_controller.rb
class DomosController < ApplicationController
  def show
    @domo = Domo.find_by(params[:id])
  end

  def new
    @domo = Domo.new
  end

  def edit
  end

  def destroy
  end

  def top
  end

  def create
    @domo = Domo.new(domo_params)

    if @domo.save
      render :show
    else
      render :new
    end
  end

  def login
  end

  def update
    @domo = Domo.update(domo_params)

    
  end


  private
  
  def domo_params
    params.require(:domo).permit(:name, :email, :password_digest)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/domos_helper.rb
module DomosHelper
end

app/views/domos/_fm.html.erb
<%= form_for(login_domos_path) do |f| %>

  <div class="field">
    

    <%= f.label :email, 'Email:' %>
    <%= f.text_field :email, size: 20, maxlength:50 %> <br />

    <%= f.submit 'ログイン' %>

  </div>

<% end %>

app/views/domos/_form.html.erb
<%= form_for(domo) do |f| %>

  <div class="field">
    <%= f.label :name, 'Name:' %>
    <%= f.text_field :name, size: 20, maxlength:25 %> <br />

    <%= f.label :email, 'Email:' %>
    <%= f.text_field :email, size: 20, maxlength:50 %> <br />

    <%= f.submit '登録' %>

  </div>

<% end %>

app/views/domos/edit.html.erb
<h1>編集</h1>

<%= render 'form', domo: @domo %>

app/views/domos/login.html.erb
<h1>ログイン</h1>

<%= render 'fm', domo: @domo %>

<%= link_to 'Home', top_domos_path %>
<%= link_to 'New Account Page', new_domo_path %>

app/views/domos/new.html.erb
<h1>アカウント作成</h1>

<%= render 'form', domo: @domo %>

<%= link_to 'Home', top_domos_path %>
<%= link_to 'Log-in Page', login_domos_path %>

app/views/domos/show.html.erb
<p>
  <strong> Name: </strong>
  <%= @domo.name %>
</p>

 

app/views/domos/top.html.erb
<h1>あなたの作品と紹介をシンプルに表示
</h1>


<%= link_to_if @user.nil?, 'サインイン', controller: :domos, action: :new do |name|
  link to 'ログイン', controller: :domos, action: :login 
end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Firstapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>